### ISSUE TITLE
Terminal penceresi

### ISSUE THREAD

**Issue by yilmazmuhammed** [eminfedar/debins#2]
Uygulama kurulurken teminal açaması açılmıyor, orada da açılsa güzel olur sanki :slightly_smiling_face:

**Comment by eminfedar** [comment]
Kapatılabilir yaptım mesaj ekranını, kapatıp terminali görebilirsiniz. (bir sonraki sürümde)

**Comment by yilmazmuhammed** [comment]
Teşekkürler :)
