### ISSUE TITLE
Terminal Penceresi

### ISSUE THREAD

**Issue by yilmazmuhammed** [eminfedar/debins#3]
Uygulama kurduktan sonra terminal penceresini açmayı denedim. Şöyle bir görüntü oluştu:

![screenshot_20181023_230551](https://user-images.githubusercontent.com/30446732/47387582-74966380-d718-11e8-901a-c571eb57acba.png)

**Comment by eminfedar** [comment]
Bu zannediyorum Qt'den kaynaklanıyor, herhalde 5.9.x ile düzeltmişlerdir fakat o da bir sonraki Pardus sürümünde desteklenecek zannımca :)

**Comment by yilmazmuhammed** [comment]
Açıklama için teşekkür ederim. 
Bu arada uygulama görüntüsü Ubuntun18.04'tendi 🙈

**Comment by eminfedar** [comment]
Benim 5.7'de derleyişimden de kaynaklanıyor olabilir, aynı problemi ben de test ederken çok defa yaşadım ama tamamen raslantısal oluşuyor, yazdığım kodda bir sorun olmadığını düşünüyorum :) fark edilirse elbette düzeltilebilir :)
